# Generated by Django 5.0b1 on 2023-11-22 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255, verbose_name="city")),
                ("street", models.CharField(max_length=255, verbose_name="street")),
                (
                    "house",
                    models.CharField(max_length=10, null=True, verbose_name="house"),
                ),
                (
                    "apartment",
                    models.CharField(
                        max_length=10, null=True, verbose_name="apartment"
                    ),
                ),
                ("comment", models.TextField(null=True, verbose_name="comment")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
