# Generated by Django 5.0b1 on 2023-11-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaqQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(verbose_name="question")),
                ("answer", models.CharField(verbose_name="answer")),
                ("is_published", models.BooleanField(verbose_name="is_published")),
            ],
        ),
    ]
